
# parsetab.py
# This file is automatically generated. Do not edit.
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'DIGIT AMPM COLONtime : DIGIT AMPM\n        | DIGIT COLON DIGIT\n        | DIGIT COLON DIGIT AMPM'
    
_lr_action_items = {'AMPM':([1,5,],[3,6,]),'$end':([2,3,5,6,],[0,-1,-2,-3,]),'DIGIT':([0,4,],[1,5,]),'COLON':([1,],[4,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'time':([0,],[2,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> time","S'",1,None,None,None),
  ('time -> DIGIT AMPM','time',2,'p_time','timeyacc.py',13),
  ('time -> DIGIT COLON DIGIT','time',3,'p_time','timeyacc.py',14),
  ('time -> DIGIT COLON DIGIT AMPM','time',4,'p_time','timeyacc.py',15),
]
